apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terra
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terra
subjects:
  - kind: ServiceAccount
    name: terra
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terra
subjects:
  - kind: ServiceAccount
    name: terra
    namespace: argocd
