apiVersion: apps/v1
kind: Deployment
metadata:
  name: terra
  namespace: argocd
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: terra

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      annotations:
        # Allow for footprint consolidation
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: terra

    spec:
      serviceAccountName: terra
      nodeSelector:
        {{- range $key, $value := .Values.terra.node_selector.labels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- if .Values.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      {{- end }}
      containers:
        - name: terra
          imagePullPolicy: Always
          image: {{.Values.registry}}/{{ .Values.terra.image }}
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8000
              name: endpoint
