apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: terra
  namespace: argocd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: terra
  minReplicas: {{ .Values.terra.autoscaling.min_replicas }}
  maxReplicas: {{ .Values.terra.autoscaling.max_replicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 10
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: terra
        target:
          type: Utilization
          averageUtilization: 50
