apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workstation-logs.juno-innovations.com
spec:
  group: juno-innovations.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                entries:
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      session:
                        type: string
                      project:
                        type: string
                      start:
                        type: string
                      end:
                        type: string
  scope: Cluster
  names:
    plural: workstation-logs
    singular: workstation-log
    kind: WorkstationLog
