---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-gatherer-token-binding
subjects:
  - kind: ServiceAccount
    name: metrics-gatherer
    namespace: argocd
roleRef:
  name: metrics-gatherer-token-creator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-gatherer-binding
subjects:
  - kind: ServiceAccount
    name: metrics-gatherer
    namespace: argocd
roleRef:
  name: metrics-gatherer-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-metrics-reader-binding
subjects:
  - kind: ServiceAccount
    name: metrics-gatherer
    namespace: argocd
roleRef:
  name: node-metrics-reader
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-gatherer-rhea-config-reader-binding
subjects:
  - kind: ServiceAccount
    name: metrics-gatherer
    namespace: argocd
roleRef:
  name: metrics-gatherer-rhea-config-reader
  kind: Role
  apiGroup: rbac.authorization.k8s.io
