apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-gatherer
  namespace: argocd
  labels:
    juno-innovations.com/service-deployment: "metrics-gatherer"
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: metrics-gatherer

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      annotations:
        # Allow for footprint consolidation
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
{{- range $key, $value := .Values.metricsGatherer.extra_annotations }}
        {{ $key }}: "{{ $value }}"
{{- end }}
      labels:
        app: metrics-gatherer

    spec:
      {{- if .Values.metricsGatherer.tolerations }}
      tolerations:
        {{- toYaml .Values.metricsGatherer.tolerations | nindent 8 }}
      {{- end }}
      serviceAccountName: metrics-gatherer
      nodeSelector:
        {{- range $key, $value := .Values.metricsGatherer.node_selector.labels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- if .Values.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      {{- end }}
      containers:
        - name: metrics-gatherer
          imagePullPolicy: {{ .Values.pull_policy }}
          image: "{{ .Values.metricsGatherer.image.registry }}/{{ .Values.metricsGatherer.image.repository }}:{{ .Values.metricsGatherer.image.tag }}"
          {{- if .Values.metricsGatherer.resources }}
          env:
            {{- range .Values.metricsGatherer.env }}
              - name: {{ .name | quote }}
                value: {{ .value | quote }}
            {{- end }}
          resources:
            {{- if .Values.metricsGatherer.resources.requests }}
            requests:
              {{- toYaml .Values.metricsGatherer.resources.requests | nindent 14 }}
            {{- end }}
            {{- if .Values.metricsGatherer.resources.limits }}
            limits:
              {{- toYaml .Values.metricsGatherer.resources.limits | nindent 14 }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 8000
              name: endpoint
        - name: rhea
          image: "{{ .Values.rhea.image.registry }}/{{ .Values.rhea.image.repository }}:{{ .Values.rhea.image.tag }}"
          imagePullPolicy: {{ .Values.pull_policy }}
          env:
          {{- range .Values.rhea.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: 13000
              name: auth
          livenessProbe:
            httpGet:
              path: /.health
              port: 13000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /.health
              port: 13000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.rhea.resources | nindent 12 }}
