apiVersion: v1
kind: Service
metadata:
  name: metrics-gatherer
  namespace: argocd
spec:
  selector:
    app: metrics-gatherer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend
