apiVersion: batch/v1
kind: Job
metadata:
  name: ensure-gateway-cert
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      serviceAccountName: argocd-application-controller
      restartPolicy: OnFailure
      containers:
      - name: cert-generator
        # ToDo: make this one of our images
        image: bitnamilegacy/kubectl:1.33.4-debian-12-r0
        env:
        - name: ORION_HOSTNAME
          value: "{{ .Values.host }}"
        - name: ORION_TLS_SECRET
          value: "{{ .Values.gateway.tlsSecretName }}"
        command:
          - /bin/bash
          - -c
          - |
{{ .Files.Get "files/gateway/ensure-gateway-cert.sh" | indent 12 }}
