apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: orion-tls-redirect
  namespace: argocd
spec:
  parentRefs:
    - name: "{{ .Values.gateway.name }}"
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
