apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: titan
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: titan
subjects:
  - kind: ServiceAccount
    name: titan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: titan
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: titan
subjects:
  - kind: ServiceAccount
    name: titan
    namespace: argocd
