apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-systempolicy
  namespace: argocd
  labels:
    juno.cedar.autoload: "true"
data:
  policies.cedar: |-
{{ .Files.Get "files/rhea/policies.cedar" | indent 4 }}
