apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-systempolicy
  namespace: {{ .Values.namespace }}
  labels:
    juno.cedar.system: "true"
data:
  policies.cedar: |-
{{ .Files.Get "files/rhea/system-policies.cedar" | indent 4 }}
