{{ if eq .Values.ingressController "cilium" }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: genesis-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: cilium-gateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: genesis-route
  namespace: {{ .Release.Namespace }}
spec:
  hostnames:
    - {{ .Values.host }}
  parentRefs:
    - name: genesis-gateway
      namespace: {{ .Release.Namespace }}
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: genesis
          namespace: {{ .Release.Namespace }}
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: genesis
          namespace: {{ .Release.Namespace }}
          port: 8000
      filters:
        - type: ExtensionRef
          extensionRef:
            name: genesis-auth
            kind: SecurityPolicy
---
apiVersion: gateway.networking.k8s.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: genesis-auth
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: genesis-gateway
  extAuth:
    http:
      url: "http://genesis.{{ .Release.Namespace }}.svc.cluster.local:3000/api/socket-auth/"
{{ end }}