apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: genesis
  namespace: argocd
spec:
  parentRefs:
    - name: "{{ .Values.gateway.name }}"
      namespace: "{{ .Values.gateway.namespace }}"
      sectionName: "https"
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: genesis
          port: 3000
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: genesis
          port: 8000
