apiVersion: apps/v1
kind: Deployment
metadata:
  name: genesis
  namespace: argocd
  annotations:
{{- range $key, $value := .Values.extra_annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: genesis
  template:
    metadata:
      labels:
        app: genesis
      annotations:
        {{- range $key, $value := .Values.extra_annotations }}
          {{ $key }}: "{{ $value }}"
        {{- end }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      serviceAccountName: genesis
      {{- if .Values.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      {{- end }}
      {{- if .Values.node_selector.enable }}
      nodeSelector:
        {{- range $key, $value := .Values.node_selector.labels }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
      containers:
        - name: genesis
          image: "{{ .Values.registry }}/{{ .Values.image}}"
          imagePullPolicy: {{ .Values.pull_policy }}
          env:
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: token
                  name: juno-auth-secret
            - name: GALAXY
              value: "Milky Way"
            - name: ICON
              value: "/universe/assets/galaxy-1.webp"
          {{- if .Values.image_pull_secret }}
            - name: IMAGE_PULL_SECRET
              value: {{ .Values.image_pull_secret }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
          ports:
            - containerPort: 3000
              name: frontend
            - containerPort: 8000
              name: backend
