apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    juno-innovations.com/ansible-playbook: juno-playbook-k3s-provision
  name: juno-playbook-k3s-provision
  namespace: argocd
data:
  ee-image: junoinnovations/ansible-ee:main
  playbook.yml: |
{{ .Files.Get "files/genesis/juno-playbook-k3s-provision.yml" | indent 4 }}
