apiVersion: v1
kind: Service
metadata:
  name: genesis
  namespace: argocd
spec:
  selector:
    app: genesis
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: frontend
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: backend
